version: "2"
services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./server/sites:/etc/nginx/conf.d
      - ./server/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./server/conf/php.ini:/etc/php7.1/fpm/conf.d/40-custom.ini
      - ./server/conf/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./server/logs:/var/logs:ro
    volumes_from:
      - php
    environment:
      - VIRTUAL_HOST=squarejazz

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    environment:
      - DEFAULT_HOST=squarejazz
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  php:
    build: .
    image: yavin/alpine-php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www
      - ./www:/application

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
